// Store data with sample product prices
// Prices are in EUR (€)

// Product categories
const categories = {
    "zuivel": "Zuivel (Dairy)",
    "brood-bakkerij": "Brood & Bakkerij (Bread & Bakery)",
    "vlees-vis": "Vlees & Vis (Meat & Fish)",
    "groenten-fruit": "Groenten & Fruit (Vegetables & Fruit)",
    "ontbijtgranen": "Ontbijtgranen (Breakfast Cereals)",
    "rijst-pasta": "Rijst & Pasta (Rice & Pasta)",
    "dranken": "Dranken (Beverages)",
    "kruiden-specerijen": "Kruiden & Specerijen (Herbs & Spices)"
};

// Available products with categories and brand options
const availableProducts = {
    // Zuivel (Dairy)
    "milk": { name: "Milk (1L)", category: "zuivel", hasHouseBrand: true, hasPremiumBrand: true },
    "butter": { name: "Butter (250g)", category: "zuivel", hasHouseBrand: true, hasPremiumBrand: true },
    "cheese": { name: "Cheese (200g)", category: "zuivel", hasHouseBrand: true, hasPremiumBrand: true },
    "yogurt": { name: "Yogurt (500g)", category: "zuivel", hasHouseBrand: true, hasPremiumBrand: true },
    
    // Brood & Bakkerij
    "bread": { name: "Bread (800g)", category: "brood-bakkerij", hasHouseBrand: true, hasPremiumBrand: true },
    
    // Vlees & Vis
    "eggs": { name: "Eggs (10 pieces)", category: "vlees-vis", hasHouseBrand: true, hasPremiumBrand: true },
    "chicken": { name: "Chicken (1kg)", category: "vlees-vis", hasHouseBrand: true, hasPremiumBrand: true },
    
    // Groenten & Fruit
    "apples": { name: "Apples (1kg)", category: "groenten-fruit", hasHouseBrand: true, hasPremiumBrand: true },
    "bananas": { name: "Bananas (1kg)", category: "groenten-fruit", hasHouseBrand: true, hasPremiumBrand: true },
    "tomatoes": { name: "Tomatoes (1kg)", category: "groenten-fruit", hasHouseBrand: true, hasPremiumBrand: true },
    "potatoes": { name: "Potatoes (2kg)", category: "groenten-fruit", hasHouseBrand: true, hasPremiumBrand: true },
    
    // Ontbijtgranen
    "cornflakes": { name: "Cornflakes (500g)", category: "ontbijtgranen", hasHouseBrand: true, hasPremiumBrand: true },
    "muesli": { name: "Muesli (500g)", category: "ontbijtgranen", hasHouseBrand: true, hasPremiumBrand: true },
    
    // Rijst & Pasta
    "rice": { name: "Rice (1kg)", category: "rijst-pasta", hasHouseBrand: true, hasPremiumBrand: true },
    "pasta": { name: "Pasta (500g)", category: "rijst-pasta", hasHouseBrand: true, hasPremiumBrand: true },
    
    // Dranken
    "coffee": { name: "Coffee (250g)", category: "dranken", hasHouseBrand: true, hasPremiumBrand: true },
    "tea": { name: "Tea (20 bags)", category: "dranken", hasHouseBrand: true, hasPremiumBrand: true },
    
    // Kruiden & Specerijen
    "sugar": { name: "Sugar (1kg)", category: "kruiden-specerijen", hasHouseBrand: true, hasPremiumBrand: false },
    "flour": { name: "Flour (1kg)", category: "kruiden-specerijen", hasHouseBrand: true, hasPremiumBrand: false },
    "oil": { name: "Olive Oil (750ml)", category: "kruiden-specerijen", hasHouseBrand: true, hasPremiumBrand: true },
    "salt": { name: "Salt (1kg)", category: "kruiden-specerijen", hasHouseBrand: true, hasPremiumBrand: false },
    "pepper": { name: "Pepper (50g)", category: "kruiden-specerijen", hasHouseBrand: true, hasPremiumBrand: true }
};

const stores = [
    {
        name: "Colruyt (Collect&Go)",
        type: "traditional",
        url: "https://www.collectandgo.be",
        products: {
            "milk": { house: 0.89, houseBrand: "Boni Selection", premium: 1.29, premiumBrand: "Inza" },
            "bread": { house: 1.19, houseBrand: "Boni Selection", premium: 1.89, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 2.49, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Columbus" },
            "butter": { house: 2.29, houseBrand: "Boni Selection", premium: 3.29, premiumBrand: "Lurpak" },
            "cheese": { house: 3.99, houseBrand: "Boni Selection", premium: 5.99, premiumBrand: "Wynendale" },
            "chicken": { house: 5.99, houseBrand: "Boni Selection", premium: 8.99, premiumBrand: "Loué" },
            "apples": { house: 1.79, houseBrand: "Boni Selection", premium: 2.49, premiumBrand: "Pink Lady" },
            "bananas": { house: 1.29, houseBrand: "Boni Selection", premium: 1.79, premiumBrand: "Chiquita" },
            "tomatoes": { house: 2.19, houseBrand: "Boni Selection", premium: 2.99, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 1.99, houseBrand: "Boni Selection", premium: 2.69, premiumBrand: "Bintje Premium" },
            "rice": { house: 2.49, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 0.99, houseBrand: "Boni Selection", premium: 1.49, premiumBrand: "Barilla" },
            "yogurt": { house: 1.49, houseBrand: "Boni Selection", premium: 2.19, premiumBrand: "Danone" },
            "coffee": { house: 4.99, houseBrand: "Boni Selection", premium: 7.99, premiumBrand: "Nespresso" },
            "tea": { house: 2.29, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Lipton" },
            "sugar": { house: 1.19, houseBrand: "Boni Selection" },
            "flour": { house: 0.89, houseBrand: "Boni Selection" },
            "oil": { house: 3.49, houseBrand: "Boni Selection", premium: 5.99, premiumBrand: "Bertolli" },
            "salt": { house: 0.79, houseBrand: "Boni Selection" },
            "pepper": { house: 1.99, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Ducros" },
            "cornflakes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Kellogg's" },
            "muesli": { house: 3.29, houseBrand: "Boni Selection", premium: 4.99, premiumBrand: "Jordans" }
        }
    },
    {
        name: "Delhaize",
        type: "traditional",
        url: "https://www.delhaize.be",
        products: {
            "milk": { house: 0.95, houseBrand: "Boni Selection", premium: 1.38, premiumBrand: "Inza" },
            "bread": { house: 1.29, houseBrand: "Boni Selection", premium: 1.87, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 2.69, houseBrand: "Boni Selection", premium: 3.9, premiumBrand: "Columbus" },
            "butter": { house: 2.49, houseBrand: "Boni Selection", premium: 3.61, premiumBrand: "Lurpak" },
            "cheese": { house: 4.29, houseBrand: "Boni Selection", premium: 6.22, premiumBrand: "Wynendale" },
            "chicken": { house: 6.49, houseBrand: "Boni Selection", premium: 9.41, premiumBrand: "Loué" },
            "apples": { house: 1.99, houseBrand: "Boni Selection", premium: 2.89, premiumBrand: "Pink Lady" },
            "bananas": { house: 1.39, houseBrand: "Boni Selection", premium: 2.02, premiumBrand: "Chiquita" },
            "tomatoes": { house: 2.39, houseBrand: "Boni Selection", premium: 3.47, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 2.19, houseBrand: "Boni Selection", premium: 3.18, premiumBrand: "Bintje Premium" },
            "rice": { house: 2.69, houseBrand: "Boni Selection", premium: 3.9, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 1.09, houseBrand: "Boni Selection", premium: 1.58, premiumBrand: "Barilla" },
            "yogurt": { house: 1.59, houseBrand: "Boni Selection", premium: 2.31, premiumBrand: "Danone" },
            "coffee": { house: 5.49, houseBrand: "Boni Selection", premium: 7.96, premiumBrand: "Nespresso" },
            "tea": { house: 2.49, houseBrand: "Boni Selection", premium: 3.61, premiumBrand: "Lipton" },
            "sugar": { house: 1.29, houseBrand: "Boni Selection" },
            "flour": { house: 0.99, houseBrand: "Boni Selection" },
            "oil": { house: 3.79, houseBrand: "Boni Selection", premium: 5.5, premiumBrand: "Bertolli" },
            "salt": { house: 0.89, houseBrand: "Boni Selection" },
            "pepper": { house: 1.99, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Ducros" },
            "cornflakes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Kellogg's" },
            "muesli": { house: 3.29, houseBrand: "Boni Selection", premium: 4.99, premiumBrand: "Jordans" }
        }
    },
    {
        name: "Carrefour",
        type: "traditional",
        url: "https://www.carrefour.be",
        products: {
            "milk": { house: 0.92, houseBrand: "Boni Selection", premium: 1.33, premiumBrand: "Inza" },
            "bread": { house: 1.25, houseBrand: "Boni Selection", premium: 1.81, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 2.59, houseBrand: "Boni Selection", premium: 3.76, premiumBrand: "Columbus" },
            "butter": { house: 2.39, houseBrand: "Boni Selection", premium: 3.47, premiumBrand: "Lurpak" },
            "cheese": { house: 4.19, houseBrand: "Boni Selection", premium: 6.08, premiumBrand: "Wynendale" },
            "chicken": { house: 6.29, houseBrand: "Boni Selection", premium: 9.12, premiumBrand: "Loué" },
            "apples": { house: 1.89, houseBrand: "Boni Selection", premium: 2.74, premiumBrand: "Pink Lady" },
            "bananas": { house: 1.35, houseBrand: "Boni Selection", premium: 1.96, premiumBrand: "Chiquita" },
            "tomatoes": { house: 2.29, houseBrand: "Boni Selection", premium: 3.32, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 2.09, houseBrand: "Boni Selection", premium: 3.03, premiumBrand: "Bintje Premium" },
            "rice": { house: 2.59, houseBrand: "Boni Selection", premium: 3.76, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 1.05, houseBrand: "Boni Selection", premium: 1.52, premiumBrand: "Barilla" },
            "yogurt": { house: 1.55, houseBrand: "Boni Selection", premium: 2.25, premiumBrand: "Danone" },
            "coffee": { house: 5.29, houseBrand: "Boni Selection", premium: 7.67, premiumBrand: "Nespresso" },
            "tea": { house: 2.39, houseBrand: "Boni Selection", premium: 3.47, premiumBrand: "Lipton" },
            "sugar": { house: 1.25, houseBrand: "Boni Selection" },
            "flour": { house: 0.95, houseBrand: "Boni Selection" },
            "oil": { house: 3.69, houseBrand: "Boni Selection", premium: 5.35, premiumBrand: "Bertolli" },
            "salt": { house: 0.85, houseBrand: "Boni Selection" },
            "pepper": { house: 1.99, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Ducros" },
            "cornflakes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Kellogg's" },
            "muesli": { house: 3.29, houseBrand: "Boni Selection", premium: 4.99, premiumBrand: "Jordans" }
        }
    },
    {
        name: "Albert Heijn",
        type: "traditional",
        url: "https://www.ah.nl",
        products: {
            "milk": { house: 0.93, houseBrand: "Boni Selection", premium: 1.35, premiumBrand: "Inza" },
            "bread": { house: 1.35, houseBrand: "Boni Selection", premium: 1.96, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 2.79, houseBrand: "Boni Selection", premium: 4.05, premiumBrand: "Columbus" },
            "butter": { house: 2.59, houseBrand: "Boni Selection", premium: 3.76, premiumBrand: "Lurpak" },
            "cheese": { house: 4.49, houseBrand: "Boni Selection", premium: 6.51, premiumBrand: "Wynendale" },
            "chicken": { house: 6.69, houseBrand: "Boni Selection", premium: 9.7, premiumBrand: "Loué" },
            "apples": { house: 2.09, houseBrand: "Boni Selection", premium: 3.03, premiumBrand: "Pink Lady" },
            "bananas": { house: 1.45, houseBrand: "Boni Selection", premium: 2.1, premiumBrand: "Chiquita" },
            "tomatoes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.61, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 2.29, houseBrand: "Boni Selection", premium: 3.32, premiumBrand: "Bintje Premium" },
            "rice": { house: 2.79, houseBrand: "Boni Selection", premium: 4.05, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 1.15, houseBrand: "Boni Selection", premium: 1.67, premiumBrand: "Barilla" },
            "yogurt": { house: 1.69, houseBrand: "Boni Selection", premium: 2.45, premiumBrand: "Danone" },
            "coffee": { house: 5.69, houseBrand: "Boni Selection", premium: 8.25, premiumBrand: "Nespresso" },
            "tea": { house: 2.59, houseBrand: "Boni Selection", premium: 3.76, premiumBrand: "Lipton" },
            "sugar": { house: 1.35, houseBrand: "Boni Selection" },
            "flour": { house: 1.05, houseBrand: "Boni Selection" },
            "oil": { house: 3.89, houseBrand: "Boni Selection", premium: 5.64, premiumBrand: "Bertolli" },
            "salt": { house: 0.95, houseBrand: "Boni Selection" },
            "pepper": { house: 1.99, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Ducros" },
            "cornflakes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Kellogg's" },
            "muesli": { house: 3.29, houseBrand: "Boni Selection", premium: 4.99, premiumBrand: "Jordans" }
        }
    },
    {
        name: "Jumbo",
        type: "traditional",
        url: "https://www.jumbo.com",
        products: {
            "milk": { house: 0.91, houseBrand: "Boni Selection", premium: 1.32, premiumBrand: "Inza" },
            "bread": { house: 1.22, houseBrand: "Boni Selection", premium: 1.77, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 2.55, houseBrand: "Boni Selection", premium: 3.7, premiumBrand: "Columbus" },
            "butter": { house: 2.35, houseBrand: "Boni Selection", premium: 3.41, premiumBrand: "Lurpak" },
            "cheese": { house: 4.15, houseBrand: "Boni Selection", premium: 6.02, premiumBrand: "Wynendale" },
            "chicken": { house: 6.19, houseBrand: "Boni Selection", premium: 8.98, premiumBrand: "Loué" },
            "apples": { house: 1.85, houseBrand: "Boni Selection", premium: 2.68, premiumBrand: "Pink Lady" },
            "bananas": { house: 1.32, houseBrand: "Boni Selection", premium: 1.91, premiumBrand: "Chiquita" },
            "tomatoes": { house: 2.25, houseBrand: "Boni Selection", premium: 3.26, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 2.05, houseBrand: "Boni Selection", premium: 2.97, premiumBrand: "Bintje Premium" },
            "rice": { house: 2.55, houseBrand: "Boni Selection", premium: 3.7, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 1.02, houseBrand: "Boni Selection", premium: 1.48, premiumBrand: "Barilla" },
            "yogurt": { house: 1.52, houseBrand: "Boni Selection", premium: 2.2, premiumBrand: "Danone" },
            "coffee": { house: 5.19, houseBrand: "Boni Selection", premium: 7.53, premiumBrand: "Nespresso" },
            "tea": { house: 2.35, houseBrand: "Boni Selection", premium: 3.41, premiumBrand: "Lipton" },
            "sugar": { house: 1.22, houseBrand: "Boni Selection" },
            "flour": { house: 0.92, houseBrand: "Boni Selection" },
            "oil": { house: 3.59, houseBrand: "Boni Selection", premium: 5.21, premiumBrand: "Bertolli" },
            "salt": { house: 0.82, houseBrand: "Boni Selection" },
            "pepper": { house: 1.99, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Ducros" },
            "cornflakes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Kellogg's" },
            "muesli": { house: 3.29, houseBrand: "Boni Selection", premium: 4.99, premiumBrand: "Jordans" }
        }
    },
    {
        name: "Aldi",
        type: "discount",
        url: "https://www.aldi.be",
        products: {
            "milk": { house: 0.79, houseBrand: "Boni Selection", premium: 1.15, premiumBrand: "Inza" },
            "bread": { house: 1.05, houseBrand: "Boni Selection", premium: 1.52, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 2.29, houseBrand: "Boni Selection", premium: 3.32, premiumBrand: "Columbus" },
            "butter": { house: 1.99, houseBrand: "Boni Selection", premium: 2.89, premiumBrand: "Lurpak" },
            "cheese": { house: 3.49, houseBrand: "Boni Selection", premium: 5.06, premiumBrand: "Wynendale" },
            "chicken": { house: 5.49, houseBrand: "Boni Selection", premium: 7.96, premiumBrand: "Loué" },
            "apples": { house: 1.59, houseBrand: "Boni Selection", premium: 2.31, premiumBrand: "Pink Lady" },
            "bananas": { house: 1.15, houseBrand: "Boni Selection", premium: 1.67, premiumBrand: "Chiquita" },
            "tomatoes": { house: 1.99, houseBrand: "Boni Selection", premium: 2.89, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 1.79, houseBrand: "Boni Selection", premium: 2.6, premiumBrand: "Bintje Premium" },
            "rice": { house: 2.19, houseBrand: "Boni Selection", premium: 3.18, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 0.85, houseBrand: "Boni Selection", premium: 1.23, premiumBrand: "Barilla" },
            "yogurt": { house: 1.29, houseBrand: "Boni Selection", premium: 1.87, premiumBrand: "Danone" },
            "coffee": { house: 4.49, houseBrand: "Boni Selection", premium: 6.51, premiumBrand: "Nespresso" },
            "tea": { house: 1.99, houseBrand: "Boni Selection", premium: 2.89, premiumBrand: "Lipton" },
            "sugar": { house: 0.99, houseBrand: "Boni Selection" },
            "flour": { house: 0.75, houseBrand: "Boni Selection" },
            "oil": { house: 3.19, houseBrand: "Boni Selection", premium: 4.63, premiumBrand: "Bertolli" },
            "salt": { house: 0.65, houseBrand: "Boni Selection" },
            "pepper": { house: 1.99, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Ducros" },
            "cornflakes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Kellogg's" },
            "muesli": { house: 3.29, houseBrand: "Boni Selection", premium: 4.99, premiumBrand: "Jordans" }
        }
    },
    {
        name: "Lidl",
        type: "discount",
        url: "https://www.lidl.be",
        products: {
            "milk": { house: 0.82, houseBrand: "Boni Selection", premium: 1.19, premiumBrand: "Inza" },
            "bread": { house: 1.09, houseBrand: "Boni Selection", premium: 1.58, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 2.35, houseBrand: "Boni Selection", premium: 3.41, premiumBrand: "Columbus" },
            "butter": { house: 2.09, houseBrand: "Boni Selection", premium: 3.03, premiumBrand: "Lurpak" },
            "cheese": { house: 3.59, houseBrand: "Boni Selection", premium: 5.21, premiumBrand: "Wynendale" },
            "chicken": { house: 5.69, houseBrand: "Boni Selection", premium: 8.25, premiumBrand: "Loué" },
            "apples": { house: 1.65, houseBrand: "Boni Selection", premium: 2.39, premiumBrand: "Pink Lady" },
            "bananas": { house: 1.19, houseBrand: "Boni Selection", premium: 1.73, premiumBrand: "Chiquita" },
            "tomatoes": { house: 2.05, houseBrand: "Boni Selection", premium: 2.97, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 1.85, houseBrand: "Boni Selection", premium: 2.68, premiumBrand: "Bintje Premium" },
            "rice": { house: 2.29, houseBrand: "Boni Selection", premium: 3.32, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 0.89, houseBrand: "Boni Selection", premium: 1.29, premiumBrand: "Barilla" },
            "yogurt": { house: 1.35, houseBrand: "Boni Selection", premium: 1.96, premiumBrand: "Danone" },
            "coffee": { house: 4.69, houseBrand: "Boni Selection", premium: 6.8, premiumBrand: "Nespresso" },
            "tea": { house: 2.09, houseBrand: "Boni Selection", premium: 3.03, premiumBrand: "Lipton" },
            "sugar": { house: 1.05, houseBrand: "Boni Selection" },
            "flour": { house: 0.79, houseBrand: "Boni Selection" },
            "oil": { house: 3.29, houseBrand: "Boni Selection", premium: 4.77, premiumBrand: "Bertolli" },
            "salt": { house: 0.69, houseBrand: "Boni Selection" },
            "pepper": { house: 1.99, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Ducros" },
            "cornflakes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Kellogg's" },
            "muesli": { house: 3.29, houseBrand: "Boni Selection", premium: 4.99, premiumBrand: "Jordans" }
        }
    },
    {
        name: "Cora",
        type: "traditional",
        url: "https://www.cora.be",
        products: {
            "milk": { house: 0.94, houseBrand: "Boni Selection", premium: 1.36, premiumBrand: "Inza" },
            "bread": { house: 1.28, houseBrand: "Boni Selection", premium: 1.86, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 2.65, houseBrand: "Boni Selection", premium: 3.84, premiumBrand: "Columbus" },
            "butter": { house: 2.45, houseBrand: "Boni Selection", premium: 3.55, premiumBrand: "Lurpak" },
            "cheese": { house: 4.25, houseBrand: "Boni Selection", premium: 6.16, premiumBrand: "Wynendale" },
            "chicken": { house: 6.39, houseBrand: "Boni Selection", premium: 9.27, premiumBrand: "Loué" },
            "apples": { house: 1.95, houseBrand: "Boni Selection", premium: 2.83, premiumBrand: "Pink Lady" },
            "bananas": { house: 1.42, houseBrand: "Boni Selection", premium: 2.06, premiumBrand: "Chiquita" },
            "tomatoes": { house: 2.35, houseBrand: "Boni Selection", premium: 3.41, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 2.15, houseBrand: "Boni Selection", premium: 3.12, premiumBrand: "Bintje Premium" },
            "rice": { house: 2.65, houseBrand: "Boni Selection", premium: 3.84, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 1.08, houseBrand: "Boni Selection", premium: 1.57, premiumBrand: "Barilla" },
            "yogurt": { house: 1.58, houseBrand: "Boni Selection", premium: 2.29, premiumBrand: "Danone" },
            "coffee": { house: 5.39, houseBrand: "Boni Selection", premium: 7.82, premiumBrand: "Nespresso" },
            "tea": { house: 2.45, houseBrand: "Boni Selection", premium: 3.55, premiumBrand: "Lipton" },
            "sugar": { house: 1.28, houseBrand: "Boni Selection" },
            "flour": { house: 0.98, houseBrand: "Boni Selection" },
            "oil": { house: 3.75, houseBrand: "Boni Selection", premium: 5.44, premiumBrand: "Bertolli" },
            "salt": { house: 0.88, houseBrand: "Boni Selection" },
            "pepper": { house: 1.99, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Ducros" },
            "cornflakes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Kellogg's" },
            "muesli": { house: 3.29, houseBrand: "Boni Selection", premium: 4.99, premiumBrand: "Jordans" }
        }
    },
    {
        name: "Intermarché",
        type: "traditional",
        url: "https://www.intermarche.be",
        products: {
            "milk": { house: 0.90, houseBrand: "Boni Selection", premium: 1.3, premiumBrand: "Inza" },
            "bread": { house: 1.20, houseBrand: "Boni Selection", premium: 1.74, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 2.50, houseBrand: "Boni Selection", premium: 3.62, premiumBrand: "Columbus" },
            "butter": { house: 2.30, houseBrand: "Boni Selection", premium: 3.33, premiumBrand: "Lurpak" },
            "cheese": { house: 4.00, houseBrand: "Boni Selection", premium: 5.8, premiumBrand: "Wynendale" },
            "chicken": { house: 6.00, houseBrand: "Boni Selection", premium: 8.7, premiumBrand: "Loué" },
            "apples": { house: 1.80, houseBrand: "Boni Selection", premium: 2.61, premiumBrand: "Pink Lady" },
            "bananas": { house: 1.30, houseBrand: "Boni Selection", premium: 1.89, premiumBrand: "Chiquita" },
            "tomatoes": { house: 2.20, houseBrand: "Boni Selection", premium: 3.19, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 2.00, houseBrand: "Boni Selection", premium: 2.9, premiumBrand: "Bintje Premium" },
            "rice": { house: 2.50, houseBrand: "Boni Selection", premium: 3.62, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 1.00, houseBrand: "Boni Selection", premium: 1.45, premiumBrand: "Barilla" },
            "yogurt": { house: 1.50, houseBrand: "Boni Selection", premium: 2.17, premiumBrand: "Danone" },
            "coffee": { house: 5.00, houseBrand: "Boni Selection", premium: 7.25, premiumBrand: "Nespresso" },
            "tea": { house: 2.30, houseBrand: "Boni Selection", premium: 3.33, premiumBrand: "Lipton" },
            "sugar": { house: 1.20, houseBrand: "Boni Selection" },
            "flour": { house: 0.90, houseBrand: "Boni Selection" },
            "oil": { house: 3.50, houseBrand: "Boni Selection", premium: 5.08, premiumBrand: "Bertolli" },
            "salt": { house: 0.80, houseBrand: "Boni Selection" },
            "pepper": { house: 1.99, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Ducros" },
            "cornflakes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Kellogg's" },
            "muesli": { house: 3.29, houseBrand: "Boni Selection", premium: 4.99, premiumBrand: "Jordans" }
        }
    },
    {
        name: "Spar",
        type: "traditional",
        url: "https://www.spar.be",
        products: {
            "milk": { house: 0.97, houseBrand: "Boni Selection", premium: 1.41, premiumBrand: "Inza" },
            "bread": { house: 1.39, houseBrand: "Boni Selection", premium: 2.02, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 2.85, houseBrand: "Boni Selection", premium: 4.13, premiumBrand: "Columbus" },
            "butter": { house: 2.65, houseBrand: "Boni Selection", premium: 3.84, premiumBrand: "Lurpak" },
            "cheese": { house: 4.55, houseBrand: "Boni Selection", premium: 6.6, premiumBrand: "Wynendale" },
            "chicken": { house: 6.85, houseBrand: "Boni Selection", premium: 9.93, premiumBrand: "Loué" },
            "apples": { house: 2.15, houseBrand: "Boni Selection", premium: 3.12, premiumBrand: "Pink Lady" },
            "bananas": { house: 1.52, houseBrand: "Boni Selection", premium: 2.2, premiumBrand: "Chiquita" },
            "tomatoes": { house: 2.55, houseBrand: "Boni Selection", premium: 3.7, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 2.35, houseBrand: "Boni Selection", premium: 3.41, premiumBrand: "Bintje Premium" },
            "rice": { house: 2.85, houseBrand: "Boni Selection", premium: 4.13, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 1.19, houseBrand: "Boni Selection", premium: 1.73, premiumBrand: "Barilla" },
            "yogurt": { house: 1.75, houseBrand: "Boni Selection", premium: 2.54, premiumBrand: "Danone" },
            "coffee": { house: 5.85, houseBrand: "Boni Selection", premium: 8.48, premiumBrand: "Nespresso" },
            "tea": { house: 2.65, houseBrand: "Boni Selection", premium: 3.84, premiumBrand: "Lipton" },
            "sugar": { house: 1.39, houseBrand: "Boni Selection" },
            "flour": { house: 1.09, houseBrand: "Boni Selection" },
            "oil": { house: 3.95, houseBrand: "Boni Selection", premium: 5.73, premiumBrand: "Bertolli" },
            "salt": { house: 0.99, houseBrand: "Boni Selection" },
            "pepper": { house: 1.99, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Ducros" },
            "cornflakes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Kellogg's" },
            "muesli": { house: 3.29, houseBrand: "Boni Selection", premium: 4.99, premiumBrand: "Jordans" }
        }
    },
    {
        name: "Bio-Planet",
        type: "organic",
        url: "https://www.bio-planet.be",
        products: {
            "milk": { house: 1.49, houseBrand: "Boni Selection", premium: 2.16, premiumBrand: "Inza" },
            "bread": { house: 2.29, houseBrand: "Boni Selection", premium: 3.32, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 4.29, houseBrand: "Boni Selection", premium: 6.22, premiumBrand: "Columbus" },
            "butter": { house: 3.99, houseBrand: "Boni Selection", premium: 5.79, premiumBrand: "Lurpak" },
            "cheese": { house: 6.49, houseBrand: "Boni Selection", premium: 9.41, premiumBrand: "Wynendale" },
            "chicken": { house: 9.99, houseBrand: "Boni Selection", premium: 14.49, premiumBrand: "Loué" },
            "apples": { house: 2.99, houseBrand: "Boni Selection", premium: 4.34, premiumBrand: "Pink Lady" },
            "bananas": { house: 2.19, houseBrand: "Boni Selection", premium: 3.18, premiumBrand: "Chiquita" },
            "tomatoes": { house: 3.49, houseBrand: "Boni Selection", premium: 5.06, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 2.99, houseBrand: "Boni Selection", premium: 4.34, premiumBrand: "Bintje Premium" },
            "rice": { house: 3.99, houseBrand: "Boni Selection", premium: 5.79, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 1.99, houseBrand: "Boni Selection", premium: 2.89, premiumBrand: "Barilla" },
            "yogurt": { house: 2.49, houseBrand: "Boni Selection", premium: 3.61, premiumBrand: "Danone" },
            "coffee": { house: 8.99, houseBrand: "Boni Selection", premium: 13.04, premiumBrand: "Nespresso" },
            "tea": { house: 4.49, houseBrand: "Boni Selection", premium: 6.51, premiumBrand: "Lipton" },
            "sugar": { house: 2.29, houseBrand: "Boni Selection" },
            "flour": { house: 1.79, houseBrand: "Boni Selection" },
            "oil": { house: 5.99, houseBrand: "Boni Selection", premium: 8.69, premiumBrand: "Bertolli" },
            "salt": { house: 1.49, houseBrand: "Boni Selection" },
            "pepper": { house: 1.99, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Ducros" },
            "cornflakes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Kellogg's" },
            "muesli": { house: 3.29, houseBrand: "Boni Selection", premium: 4.99, premiumBrand: "Jordans" }
        }
    },
    {
        name: "OKay",
        type: "discount",
        url: "https://www.okay.be",
        products: {
            "milk": { house: 0.85, houseBrand: "Boni Selection", premium: 1.23, premiumBrand: "Inza" },
            "bread": { house: 1.15, houseBrand: "Boni Selection", premium: 1.67, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 2.39, houseBrand: "Boni Selection", premium: 3.47, premiumBrand: "Columbus" },
            "butter": { house: 2.15, houseBrand: "Boni Selection", premium: 3.12, premiumBrand: "Lurpak" },
            "cheese": { house: 3.69, houseBrand: "Boni Selection", premium: 5.35, premiumBrand: "Wynendale" },
            "chicken": { house: 5.79, houseBrand: "Boni Selection", premium: 8.4, premiumBrand: "Loué" },
            "apples": { house: 1.69, houseBrand: "Boni Selection", premium: 2.45, premiumBrand: "Pink Lady" },
            "bananas": { house: 1.25, houseBrand: "Boni Selection", premium: 1.81, premiumBrand: "Chiquita" },
            "tomatoes": { house: 2.09, houseBrand: "Boni Selection", premium: 3.03, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 1.89, houseBrand: "Boni Selection", premium: 2.74, premiumBrand: "Bintje Premium" },
            "rice": { house: 2.39, houseBrand: "Boni Selection", premium: 3.47, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 0.92, houseBrand: "Boni Selection", premium: 1.33, premiumBrand: "Barilla" },
            "yogurt": { house: 1.39, houseBrand: "Boni Selection", premium: 2.02, premiumBrand: "Danone" },
            "coffee": { house: 4.79, houseBrand: "Boni Selection", premium: 6.95, premiumBrand: "Nespresso" },
            "tea": { house: 2.15, houseBrand: "Boni Selection", premium: 3.12, premiumBrand: "Lipton" },
            "sugar": { house: 1.09, houseBrand: "Boni Selection" },
            "flour": { house: 0.82, houseBrand: "Boni Selection" },
            "oil": { house: 3.39, houseBrand: "Boni Selection", premium: 4.92, premiumBrand: "Bertolli" },
            "salt": { house: 0.72, houseBrand: "Boni Selection" },
            "pepper": { house: 1.99, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Ducros" },
            "cornflakes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Kellogg's" },
            "muesli": { house: 3.29, houseBrand: "Boni Selection", premium: 4.99, premiumBrand: "Jordans" }
        }
    },
    {
        name: "Cru",
        type: "specialty",
        url: "https://www.cru.be",
        products: {
            "milk": { house: 1.29, houseBrand: "Boni Selection", premium: 1.87, premiumBrand: "Inza" },
            "bread": { house: 1.99, houseBrand: "Boni Selection", premium: 2.89, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 3.79, houseBrand: "Boni Selection", premium: 5.5, premiumBrand: "Columbus" },
            "butter": { house: 3.49, houseBrand: "Boni Selection", premium: 5.06, premiumBrand: "Lurpak" },
            "cheese": { house: 5.99, houseBrand: "Boni Selection", premium: 8.69, premiumBrand: "Wynendale" },
            "chicken": { house: 8.99, houseBrand: "Boni Selection", premium: 13.04, premiumBrand: "Loué" },
            "apples": { house: 2.69, houseBrand: "Boni Selection", premium: 3.9, premiumBrand: "Pink Lady" },
            "bananas": { house: 1.89, houseBrand: "Boni Selection", premium: 2.74, premiumBrand: "Chiquita" },
            "tomatoes": { house: 3.19, houseBrand: "Boni Selection", premium: 4.63, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 2.69, houseBrand: "Boni Selection", premium: 3.9, premiumBrand: "Bintje Premium" },
            "rice": { house: 3.49, houseBrand: "Boni Selection", premium: 5.06, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 1.69, houseBrand: "Boni Selection", premium: 2.45, premiumBrand: "Barilla" },
            "yogurt": { house: 2.19, houseBrand: "Boni Selection", premium: 3.18, premiumBrand: "Danone" },
            "coffee": { house: 7.99, houseBrand: "Boni Selection", premium: 11.59, premiumBrand: "Nespresso" },
            "tea": { house: 3.99, houseBrand: "Boni Selection", premium: 5.79, premiumBrand: "Lipton" },
            "sugar": { house: 1.99, houseBrand: "Boni Selection" },
            "flour": { house: 1.49, houseBrand: "Boni Selection" },
            "oil": { house: 5.49, houseBrand: "Boni Selection", premium: 7.96, premiumBrand: "Bertolli" },
            "salt": { house: 1.29, houseBrand: "Boni Selection" },
            "pepper": { house: 1.99, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Ducros" },
            "cornflakes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Kellogg's" },
            "muesli": { house: 3.29, houseBrand: "Boni Selection", premium: 4.99, premiumBrand: "Jordans" }
        }
    },
    {
        name: "Rayon",
        type: "online",
        url: "https://www.rayon.be",
        products: {
            "milk": { house: 0.96, houseBrand: "Boni Selection", premium: 1.39, premiumBrand: "Inza" },
            "bread": { house: 1.32, houseBrand: "Boni Selection", premium: 1.91, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 2.72, houseBrand: "Boni Selection", premium: 3.94, premiumBrand: "Columbus" },
            "butter": { house: 2.52, houseBrand: "Boni Selection", premium: 3.65, premiumBrand: "Lurpak" },
            "cheese": { house: 4.32, houseBrand: "Boni Selection", premium: 6.26, premiumBrand: "Wynendale" },
            "chicken": { house: 6.52, houseBrand: "Boni Selection", premium: 9.45, premiumBrand: "Loué" },
            "apples": { house: 2.02, houseBrand: "Boni Selection", premium: 2.93, premiumBrand: "Pink Lady" },
            "bananas": { house: 1.48, houseBrand: "Boni Selection", premium: 2.15, premiumBrand: "Chiquita" },
            "tomatoes": { house: 2.42, houseBrand: "Boni Selection", premium: 3.51, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 2.22, houseBrand: "Boni Selection", premium: 3.22, premiumBrand: "Bintje Premium" },
            "rice": { house: 2.72, houseBrand: "Boni Selection", premium: 3.94, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 1.12, houseBrand: "Boni Selection", premium: 1.62, premiumBrand: "Barilla" },
            "yogurt": { house: 1.62, houseBrand: "Boni Selection", premium: 2.35, premiumBrand: "Danone" },
            "coffee": { house: 5.52, houseBrand: "Boni Selection", premium: 8.0, premiumBrand: "Nespresso" },
            "tea": { house: 2.52, houseBrand: "Boni Selection", premium: 3.65, premiumBrand: "Lipton" },
            "sugar": { house: 1.32, houseBrand: "Boni Selection" },
            "flour": { house: 1.02, houseBrand: "Boni Selection" },
            "oil": { house: 3.82, houseBrand: "Boni Selection", premium: 5.54, premiumBrand: "Bertolli" },
            "salt": { house: 0.92, houseBrand: "Boni Selection" },
            "pepper": { house: 1.99, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Ducros" },
            "cornflakes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Kellogg's" },
            "muesli": { house: 3.29, houseBrand: "Boni Selection", premium: 4.99, premiumBrand: "Jordans" }
        }
    },
    {
        name: "Crisp",
        type: "online",
        url: "https://www.crisp.be",
        products: {
            "milk": { house: 1.05, houseBrand: "Boni Selection", premium: 1.52, premiumBrand: "Inza" },
            "bread": { house: 1.49, houseBrand: "Boni Selection", premium: 2.16, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 2.99, houseBrand: "Boni Selection", premium: 4.34, premiumBrand: "Columbus" },
            "butter": { house: 2.79, houseBrand: "Boni Selection", premium: 4.05, premiumBrand: "Lurpak" },
            "cheese": { house: 4.79, houseBrand: "Boni Selection", premium: 6.95, premiumBrand: "Wynendale" },
            "chicken": { house: 7.29, houseBrand: "Boni Selection", premium: 10.57, premiumBrand: "Loué" },
            "apples": { house: 2.29, houseBrand: "Boni Selection", premium: 3.32, premiumBrand: "Pink Lady" },
            "bananas": { house: 1.69, houseBrand: "Boni Selection", premium: 2.45, premiumBrand: "Chiquita" },
            "tomatoes": { house: 2.79, houseBrand: "Boni Selection", premium: 4.05, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.61, premiumBrand: "Bintje Premium" },
            "rice": { house: 2.99, houseBrand: "Boni Selection", premium: 4.34, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 1.29, houseBrand: "Boni Selection", premium: 1.87, premiumBrand: "Barilla" },
            "yogurt": { house: 1.89, houseBrand: "Boni Selection", premium: 2.74, premiumBrand: "Danone" },
            "coffee": { house: 6.29, houseBrand: "Boni Selection", premium: 9.12, premiumBrand: "Nespresso" },
            "tea": { house: 2.89, houseBrand: "Boni Selection", premium: 4.19, premiumBrand: "Lipton" },
            "sugar": { house: 1.49, houseBrand: "Boni Selection" },
            "flour": { house: 1.19, houseBrand: "Boni Selection" },
            "oil": { house: 4.19, houseBrand: "Boni Selection", premium: 6.08, premiumBrand: "Bertolli" },
            "salt": { house: 1.09, houseBrand: "Boni Selection" },
            "pepper": { house: 1.99, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Ducros" },
            "cornflakes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Kellogg's" },
            "muesli": { house: 3.29, houseBrand: "Boni Selection", premium: 4.99, premiumBrand: "Jordans" }
        }
    },
    {
        name: "Ochama",
        type: "online",
        url: "https://www.ochama.com",
        products: {
            "milk": { house: 0.88, houseBrand: "Boni Selection", premium: 1.28, premiumBrand: "Inza" },
            "bread": { house: 1.18, houseBrand: "Boni Selection", premium: 1.71, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 2.48, houseBrand: "Boni Selection", premium: 3.6, premiumBrand: "Columbus" },
            "butter": { house: 2.28, houseBrand: "Boni Selection", premium: 3.31, premiumBrand: "Lurpak" },
            "cheese": { house: 3.98, houseBrand: "Boni Selection", premium: 5.77, premiumBrand: "Wynendale" },
            "chicken": { house: 5.98, houseBrand: "Boni Selection", premium: 8.67, premiumBrand: "Loué" },
            "apples": { house: 1.78, houseBrand: "Boni Selection", premium: 2.58, premiumBrand: "Pink Lady" },
            "bananas": { house: 1.28, houseBrand: "Boni Selection", premium: 1.86, premiumBrand: "Chiquita" },
            "tomatoes": { house: 2.18, houseBrand: "Boni Selection", premium: 3.16, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 1.98, houseBrand: "Boni Selection", premium: 2.87, premiumBrand: "Bintje Premium" },
            "rice": { house: 2.48, houseBrand: "Boni Selection", premium: 3.6, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 0.98, houseBrand: "Boni Selection", premium: 1.42, premiumBrand: "Barilla" },
            "yogurt": { house: 1.48, houseBrand: "Boni Selection", premium: 2.15, premiumBrand: "Danone" },
            "coffee": { house: 4.98, houseBrand: "Boni Selection", premium: 7.22, premiumBrand: "Nespresso" },
            "tea": { house: 2.28, houseBrand: "Boni Selection", premium: 3.31, premiumBrand: "Lipton" },
            "sugar": { house: 1.18, houseBrand: "Boni Selection" },
            "flour": { house: 0.88, houseBrand: "Boni Selection" },
            "oil": { house: 3.48, houseBrand: "Boni Selection", premium: 5.05, premiumBrand: "Bertolli" },
            "salt": { house: 0.78, houseBrand: "Boni Selection" },
            "pepper": { house: 1.99, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Ducros" },
            "cornflakes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Kellogg's" },
            "muesli": { house: 3.29, houseBrand: "Boni Selection", premium: 4.99, premiumBrand: "Jordans" }
        }
    },
    {
        name: "Kazidomi",
        type: "online-organic",
        url: "https://www.kazidomi.com",
        products: {
            "milk": { house: 1.39, houseBrand: "Boni Selection", premium: 2.02, premiumBrand: "Inza" },
            "bread": { house: 2.19, houseBrand: "Boni Selection", premium: 3.18, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 4.09, houseBrand: "Boni Selection", premium: 5.93, premiumBrand: "Columbus" },
            "butter": { house: 3.79, houseBrand: "Boni Selection", premium: 5.5, premiumBrand: "Lurpak" },
            "cheese": { house: 6.19, houseBrand: "Boni Selection", premium: 8.98, premiumBrand: "Wynendale" },
            "chicken": { house: 9.49, houseBrand: "Boni Selection", premium: 13.76, premiumBrand: "Loué" },
            "apples": { house: 2.79, houseBrand: "Boni Selection", premium: 4.05, premiumBrand: "Pink Lady" },
            "bananas": { house: 2.09, houseBrand: "Boni Selection", premium: 3.03, premiumBrand: "Chiquita" },
            "tomatoes": { house: 3.29, houseBrand: "Boni Selection", premium: 4.77, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 2.79, houseBrand: "Boni Selection", premium: 4.05, premiumBrand: "Bintje Premium" },
            "rice": { house: 3.79, houseBrand: "Boni Selection", premium: 5.5, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 1.89, houseBrand: "Boni Selection", premium: 2.74, premiumBrand: "Barilla" },
            "yogurt": { house: 2.39, houseBrand: "Boni Selection", premium: 3.47, premiumBrand: "Danone" },
            "coffee": { house: 8.49, houseBrand: "Boni Selection", premium: 12.31, premiumBrand: "Nespresso" },
            "tea": { house: 4.29, houseBrand: "Boni Selection", premium: 6.22, premiumBrand: "Lipton" },
            "sugar": { house: 2.19, houseBrand: "Boni Selection" },
            "flour": { house: 1.69, houseBrand: "Boni Selection" },
            "oil": { house: 5.79, houseBrand: "Boni Selection", premium: 8.4, premiumBrand: "Bertolli" },
            "salt": { house: 1.39, houseBrand: "Boni Selection" },
            "pepper": { house: 1.99, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Ducros" },
            "cornflakes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Kellogg's" },
            "muesli": { house: 3.29, houseBrand: "Boni Selection", premium: 4.99, premiumBrand: "Jordans" }
        }
    },
    {
        name: "Uber Eats (Supermarket)",
        type: "quick-commerce",
        url: "https://www.ubereats.com",
        products: {
            "milk": { house: 1.19, houseBrand: "Boni Selection", premium: 1.73, premiumBrand: "Inza" },
            "bread": { house: 1.69, houseBrand: "Boni Selection", premium: 2.45, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 3.29, houseBrand: "Boni Selection", premium: 4.77, premiumBrand: "Columbus" },
            "butter": { house: 2.99, houseBrand: "Boni Selection", premium: 4.34, premiumBrand: "Lurpak" },
            "cheese": { house: 5.09, houseBrand: "Boni Selection", premium: 7.38, premiumBrand: "Wynendale" },
            "chicken": { house: 7.79, houseBrand: "Boni Selection", premium: 11.3, premiumBrand: "Loué" },
            "apples": { house: 2.49, houseBrand: "Boni Selection", premium: 3.61, premiumBrand: "Pink Lady" },
            "bananas": { house: 1.89, houseBrand: "Boni Selection", premium: 2.74, premiumBrand: "Chiquita" },
            "tomatoes": { house: 2.99, houseBrand: "Boni Selection", premium: 4.34, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 2.69, houseBrand: "Boni Selection", premium: 3.9, premiumBrand: "Bintje Premium" },
            "rice": { house: 3.19, houseBrand: "Boni Selection", premium: 4.63, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 1.49, houseBrand: "Boni Selection", premium: 2.16, premiumBrand: "Barilla" },
            "yogurt": { house: 2.09, houseBrand: "Boni Selection", premium: 3.03, premiumBrand: "Danone" },
            "coffee": { house: 6.79, houseBrand: "Boni Selection", premium: 9.85, premiumBrand: "Nespresso" },
            "tea": { house: 3.09, houseBrand: "Boni Selection", premium: 4.48, premiumBrand: "Lipton" },
            "sugar": { house: 1.69, houseBrand: "Boni Selection" },
            "flour": { house: 1.39, houseBrand: "Boni Selection" },
            "oil": { house: 4.49, houseBrand: "Boni Selection", premium: 6.51, premiumBrand: "Bertolli" },
            "salt": { house: 1.19, houseBrand: "Boni Selection" },
            "pepper": { house: 2.69, houseBrand: "Boni Selection", premium: 3.9, premiumBrand: "Ducros" }
        }
    },
    {
        name: "Deliveroo (Supermarket)",
        type: "quick-commerce",
        url: "https://www.deliveroo.be",
        products: {
            "milk": { house: 1.15, houseBrand: "Boni Selection", premium: 1.67, premiumBrand: "Inza" },
            "bread": { house: 1.65, houseBrand: "Boni Selection", premium: 2.39, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 3.19, houseBrand: "Boni Selection", premium: 4.63, premiumBrand: "Columbus" },
            "butter": { house: 2.89, houseBrand: "Boni Selection", premium: 4.19, premiumBrand: "Lurpak" },
            "cheese": { house: 4.99, houseBrand: "Boni Selection", premium: 7.24, premiumBrand: "Wynendale" },
            "chicken": { house: 7.59, houseBrand: "Boni Selection", premium: 11.01, premiumBrand: "Loué" },
            "apples": { house: 2.39, houseBrand: "Boni Selection", premium: 3.47, premiumBrand: "Pink Lady" },
            "bananas": { house: 1.79, houseBrand: "Boni Selection", premium: 2.6, premiumBrand: "Chiquita" },
            "tomatoes": { house: 2.89, houseBrand: "Boni Selection", premium: 4.19, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 2.59, houseBrand: "Boni Selection", premium: 3.76, premiumBrand: "Bintje Premium" },
            "rice": { house: 3.09, houseBrand: "Boni Selection", premium: 4.48, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 1.45, houseBrand: "Boni Selection", premium: 2.1, premiumBrand: "Barilla" },
            "yogurt": { house: 1.99, houseBrand: "Boni Selection", premium: 2.89, premiumBrand: "Danone" },
            "coffee": { house: 6.59, houseBrand: "Boni Selection", premium: 9.56, premiumBrand: "Nespresso" },
            "tea": { house: 2.99, houseBrand: "Boni Selection", premium: 4.34, premiumBrand: "Lipton" },
            "sugar": { house: 1.65, houseBrand: "Boni Selection" },
            "flour": { house: 1.35, houseBrand: "Boni Selection" },
            "oil": { house: 4.39, houseBrand: "Boni Selection", premium: 6.37, premiumBrand: "Bertolli" },
            "salt": { house: 1.15, houseBrand: "Boni Selection" },
            "pepper": { house: 2.59, houseBrand: "Boni Selection", premium: 3.76, premiumBrand: "Ducros" }
        }
    },
    {
        name: "Flink",
        type: "quick-commerce",
        url: "https://www.goflink.com",
        products: {
            "milk": { house: 1.09, houseBrand: "Boni Selection", premium: 1.58, premiumBrand: "Inza" },
            "bread": { house: 1.55, houseBrand: "Boni Selection", premium: 2.25, premiumBrand: "Pain Jacquet" },
            "eggs": { house: 3.05, houseBrand: "Boni Selection", premium: 4.42, premiumBrand: "Columbus" },
            "butter": { house: 2.75, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Lurpak" },
            "cheese": { house: 4.85, houseBrand: "Boni Selection", premium: 7.03, premiumBrand: "Wynendale" },
            "chicken": { house: 7.35, houseBrand: "Boni Selection", premium: 10.66, premiumBrand: "Loué" },
            "apples": { house: 2.25, houseBrand: "Boni Selection", premium: 3.26, premiumBrand: "Pink Lady" },
            "bananas": { house: 1.65, houseBrand: "Boni Selection", premium: 2.39, premiumBrand: "Chiquita" },
            "tomatoes": { house: 2.75, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Tasty Tom" },
            "potatoes": { house: 2.45, houseBrand: "Boni Selection", premium: 3.55, premiumBrand: "Bintje Premium" },
            "rice": { house: 2.95, houseBrand: "Boni Selection", premium: 4.28, premiumBrand: "Uncle Ben's" },
            "pasta": { house: 1.35, houseBrand: "Boni Selection", premium: 1.96, premiumBrand: "Barilla" },
            "yogurt": { house: 1.85, houseBrand: "Boni Selection", premium: 2.68, premiumBrand: "Danone" },
            "coffee": { house: 6.35, houseBrand: "Boni Selection", premium: 9.21, premiumBrand: "Nespresso" },
            "tea": { house: 2.85, houseBrand: "Boni Selection", premium: 4.13, premiumBrand: "Lipton" },
            "sugar": { house: 1.55, houseBrand: "Boni Selection" },
            "flour": { house: 1.25, houseBrand: "Boni Selection" },
            "oil": { house: 4.25, houseBrand: "Boni Selection", premium: 6.16, premiumBrand: "Bertolli" },
            "salt": { house: 1.05, houseBrand: "Boni Selection" },
            "pepper": { house: 1.99, houseBrand: "Boni Selection", premium: 3.49, premiumBrand: "Ducros" },
            "cornflakes": { house: 2.49, houseBrand: "Boni Selection", premium: 3.99, premiumBrand: "Kellogg's" },
            "muesli": { house: 3.29, houseBrand: "Boni Selection", premium: 4.99, premiumBrand: "Jordans" }
        }
    }
];
