// Store data with sample product prices
// Prices are in EUR (€)

const stores = [
    {
        name: "Colruyt (Collect&Go)",
        type: "traditional",
        products: {
            "milk": 0.89,
            "bread": 1.19,
            "eggs": 2.49,
            "butter": 2.29,
            "cheese": 3.99,
            "chicken": 5.99,
            "apples": 1.79,
            "bananas": 1.29,
            "tomatoes": 2.19,
            "potatoes": 1.99,
            "rice": 2.49,
            "pasta": 0.99,
            "yogurt": 1.49,
            "coffee": 4.99,
            "tea": 2.29,
            "sugar": 1.19,
            "flour": 0.89,
            "oil": 3.49,
            "salt": 0.79,
            "pepper": 1.99
        }
    },
    {
        name: "Delhaize",
        type: "traditional",
        products: {
            "milk": 0.95,
            "bread": 1.29,
            "eggs": 2.69,
            "butter": 2.49,
            "cheese": 4.29,
            "chicken": 6.49,
            "apples": 1.99,
            "bananas": 1.39,
            "tomatoes": 2.39,
            "potatoes": 2.19,
            "rice": 2.69,
            "pasta": 1.09,
            "yogurt": 1.59,
            "coffee": 5.49,
            "tea": 2.49,
            "sugar": 1.29,
            "flour": 0.99,
            "oil": 3.79,
            "salt": 0.89,
            "pepper": 2.19
        }
    },
    {
        name: "Carrefour",
        type: "traditional",
        products: {
            "milk": 0.92,
            "bread": 1.25,
            "eggs": 2.59,
            "butter": 2.39,
            "cheese": 4.19,
            "chicken": 6.29,
            "apples": 1.89,
            "bananas": 1.35,
            "tomatoes": 2.29,
            "potatoes": 2.09,
            "rice": 2.59,
            "pasta": 1.05,
            "yogurt": 1.55,
            "coffee": 5.29,
            "tea": 2.39,
            "sugar": 1.25,
            "flour": 0.95,
            "oil": 3.69,
            "salt": 0.85,
            "pepper": 2.09
        }
    },
    {
        name: "Albert Heijn",
        type: "traditional",
        products: {
            "milk": 0.93,
            "bread": 1.35,
            "eggs": 2.79,
            "butter": 2.59,
            "cheese": 4.49,
            "chicken": 6.69,
            "apples": 2.09,
            "bananas": 1.45,
            "tomatoes": 2.49,
            "potatoes": 2.29,
            "rice": 2.79,
            "pasta": 1.15,
            "yogurt": 1.69,
            "coffee": 5.69,
            "tea": 2.59,
            "sugar": 1.35,
            "flour": 1.05,
            "oil": 3.89,
            "salt": 0.95,
            "pepper": 2.29
        }
    },
    {
        name: "Jumbo",
        type: "traditional",
        products: {
            "milk": 0.91,
            "bread": 1.22,
            "eggs": 2.55,
            "butter": 2.35,
            "cheese": 4.15,
            "chicken": 6.19,
            "apples": 1.85,
            "bananas": 1.32,
            "tomatoes": 2.25,
            "potatoes": 2.05,
            "rice": 2.55,
            "pasta": 1.02,
            "yogurt": 1.52,
            "coffee": 5.19,
            "tea": 2.35,
            "sugar": 1.22,
            "flour": 0.92,
            "oil": 3.59,
            "salt": 0.82,
            "pepper": 2.05
        }
    },
    {
        name: "Aldi",
        type: "discount",
        products: {
            "milk": 0.79,
            "bread": 1.05,
            "eggs": 2.29,
            "butter": 1.99,
            "cheese": 3.49,
            "chicken": 5.49,
            "apples": 1.59,
            "bananas": 1.15,
            "tomatoes": 1.99,
            "potatoes": 1.79,
            "rice": 2.19,
            "pasta": 0.85,
            "yogurt": 1.29,
            "coffee": 4.49,
            "tea": 1.99,
            "sugar": 0.99,
            "flour": 0.75,
            "oil": 3.19,
            "salt": 0.65,
            "pepper": 1.79
        }
    },
    {
        name: "Lidl",
        type: "discount",
        products: {
            "milk": 0.82,
            "bread": 1.09,
            "eggs": 2.35,
            "butter": 2.09,
            "cheese": 3.59,
            "chicken": 5.69,
            "apples": 1.65,
            "bananas": 1.19,
            "tomatoes": 2.05,
            "potatoes": 1.85,
            "rice": 2.29,
            "pasta": 0.89,
            "yogurt": 1.35,
            "coffee": 4.69,
            "tea": 2.09,
            "sugar": 1.05,
            "flour": 0.79,
            "oil": 3.29,
            "salt": 0.69,
            "pepper": 1.85
        }
    },
    {
        name: "Cora",
        type: "traditional",
        products: {
            "milk": 0.94,
            "bread": 1.28,
            "eggs": 2.65,
            "butter": 2.45,
            "cheese": 4.25,
            "chicken": 6.39,
            "apples": 1.95,
            "bananas": 1.42,
            "tomatoes": 2.35,
            "potatoes": 2.15,
            "rice": 2.65,
            "pasta": 1.08,
            "yogurt": 1.58,
            "coffee": 5.39,
            "tea": 2.45,
            "sugar": 1.28,
            "flour": 0.98,
            "oil": 3.75,
            "salt": 0.88,
            "pepper": 2.15
        }
    },
    {
        name: "Intermarché",
        type: "traditional",
        products: {
            "milk": 0.90,
            "bread": 1.20,
            "eggs": 2.50,
            "butter": 2.30,
            "cheese": 4.00,
            "chicken": 6.00,
            "apples": 1.80,
            "bananas": 1.30,
            "tomatoes": 2.20,
            "potatoes": 2.00,
            "rice": 2.50,
            "pasta": 1.00,
            "yogurt": 1.50,
            "coffee": 5.00,
            "tea": 2.30,
            "sugar": 1.20,
            "flour": 0.90,
            "oil": 3.50,
            "salt": 0.80,
            "pepper": 2.00
        }
    },
    {
        name: "Spar",
        type: "traditional",
        products: {
            "milk": 0.97,
            "bread": 1.39,
            "eggs": 2.85,
            "butter": 2.65,
            "cheese": 4.55,
            "chicken": 6.85,
            "apples": 2.15,
            "bananas": 1.52,
            "tomatoes": 2.55,
            "potatoes": 2.35,
            "rice": 2.85,
            "pasta": 1.19,
            "yogurt": 1.75,
            "coffee": 5.85,
            "tea": 2.65,
            "sugar": 1.39,
            "flour": 1.09,
            "oil": 3.95,
            "salt": 0.99,
            "pepper": 2.35
        }
    },
    {
        name: "Bio-Planet",
        type: "organic",
        products: {
            "milk": 1.49,
            "bread": 2.29,
            "eggs": 4.29,
            "butter": 3.99,
            "cheese": 6.49,
            "chicken": 9.99,
            "apples": 2.99,
            "bananas": 2.19,
            "tomatoes": 3.49,
            "potatoes": 2.99,
            "rice": 3.99,
            "pasta": 1.99,
            "yogurt": 2.49,
            "coffee": 8.99,
            "tea": 4.49,
            "sugar": 2.29,
            "flour": 1.79,
            "oil": 5.99,
            "salt": 1.49,
            "pepper": 3.99
        }
    },
    {
        name: "OKay",
        type: "discount",
        products: {
            "milk": 0.85,
            "bread": 1.15,
            "eggs": 2.39,
            "butter": 2.15,
            "cheese": 3.69,
            "chicken": 5.79,
            "apples": 1.69,
            "bananas": 1.25,
            "tomatoes": 2.09,
            "potatoes": 1.89,
            "rice": 2.39,
            "pasta": 0.92,
            "yogurt": 1.39,
            "coffee": 4.79,
            "tea": 2.15,
            "sugar": 1.09,
            "flour": 0.82,
            "oil": 3.39,
            "salt": 0.72,
            "pepper": 1.89
        }
    },
    {
        name: "Cru",
        type: "specialty",
        products: {
            "milk": 1.29,
            "bread": 1.99,
            "eggs": 3.79,
            "butter": 3.49,
            "cheese": 5.99,
            "chicken": 8.99,
            "apples": 2.69,
            "bananas": 1.89,
            "tomatoes": 3.19,
            "potatoes": 2.69,
            "rice": 3.49,
            "pasta": 1.69,
            "yogurt": 2.19,
            "coffee": 7.99,
            "tea": 3.99,
            "sugar": 1.99,
            "flour": 1.49,
            "oil": 5.49,
            "salt": 1.29,
            "pepper": 3.49
        }
    },
    {
        name: "Rayon",
        type: "online",
        products: {
            "milk": 0.96,
            "bread": 1.32,
            "eggs": 2.72,
            "butter": 2.52,
            "cheese": 4.32,
            "chicken": 6.52,
            "apples": 2.02,
            "bananas": 1.48,
            "tomatoes": 2.42,
            "potatoes": 2.22,
            "rice": 2.72,
            "pasta": 1.12,
            "yogurt": 1.62,
            "coffee": 5.52,
            "tea": 2.52,
            "sugar": 1.32,
            "flour": 1.02,
            "oil": 3.82,
            "salt": 0.92,
            "pepper": 2.22
        }
    },
    {
        name: "Crisp",
        type: "online",
        products: {
            "milk": 1.05,
            "bread": 1.49,
            "eggs": 2.99,
            "butter": 2.79,
            "cheese": 4.79,
            "chicken": 7.29,
            "apples": 2.29,
            "bananas": 1.69,
            "tomatoes": 2.79,
            "potatoes": 2.49,
            "rice": 2.99,
            "pasta": 1.29,
            "yogurt": 1.89,
            "coffee": 6.29,
            "tea": 2.89,
            "sugar": 1.49,
            "flour": 1.19,
            "oil": 4.19,
            "salt": 1.09,
            "pepper": 2.49
        }
    },
    {
        name: "Ochama",
        type: "online",
        products: {
            "milk": 0.88,
            "bread": 1.18,
            "eggs": 2.48,
            "butter": 2.28,
            "cheese": 3.98,
            "chicken": 5.98,
            "apples": 1.78,
            "bananas": 1.28,
            "tomatoes": 2.18,
            "potatoes": 1.98,
            "rice": 2.48,
            "pasta": 0.98,
            "yogurt": 1.48,
            "coffee": 4.98,
            "tea": 2.28,
            "sugar": 1.18,
            "flour": 0.88,
            "oil": 3.48,
            "salt": 0.78,
            "pepper": 1.98
        }
    },
    {
        name: "Kazidomi",
        type: "online-organic",
        products: {
            "milk": 1.39,
            "bread": 2.19,
            "eggs": 4.09,
            "butter": 3.79,
            "cheese": 6.19,
            "chicken": 9.49,
            "apples": 2.79,
            "bananas": 2.09,
            "tomatoes": 3.29,
            "potatoes": 2.79,
            "rice": 3.79,
            "pasta": 1.89,
            "yogurt": 2.39,
            "coffee": 8.49,
            "tea": 4.29,
            "sugar": 2.19,
            "flour": 1.69,
            "oil": 5.79,
            "salt": 1.39,
            "pepper": 3.79
        }
    },
    {
        name: "Uber Eats (Supermarket)",
        type: "quick-commerce",
        products: {
            "milk": 1.19,
            "bread": 1.69,
            "eggs": 3.29,
            "butter": 2.99,
            "cheese": 5.09,
            "chicken": 7.79,
            "apples": 2.49,
            "bananas": 1.89,
            "tomatoes": 2.99,
            "potatoes": 2.69,
            "rice": 3.19,
            "pasta": 1.49,
            "yogurt": 2.09,
            "coffee": 6.79,
            "tea": 3.09,
            "sugar": 1.69,
            "flour": 1.39,
            "oil": 4.49,
            "salt": 1.19,
            "pepper": 2.69
        }
    },
    {
        name: "Deliveroo (Supermarket)",
        type: "quick-commerce",
        products: {
            "milk": 1.15,
            "bread": 1.65,
            "eggs": 3.19,
            "butter": 2.89,
            "cheese": 4.99,
            "chicken": 7.59,
            "apples": 2.39,
            "bananas": 1.79,
            "tomatoes": 2.89,
            "potatoes": 2.59,
            "rice": 3.09,
            "pasta": 1.45,
            "yogurt": 1.99,
            "coffee": 6.59,
            "tea": 2.99,
            "sugar": 1.65,
            "flour": 1.35,
            "oil": 4.39,
            "salt": 1.15,
            "pepper": 2.59
        }
    },
    {
        name: "Flink",
        type: "quick-commerce",
        products: {
            "milk": 1.09,
            "bread": 1.55,
            "eggs": 3.05,
            "butter": 2.75,
            "cheese": 4.85,
            "chicken": 7.35,
            "apples": 2.25,
            "bananas": 1.65,
            "tomatoes": 2.75,
            "potatoes": 2.45,
            "rice": 2.95,
            "pasta": 1.35,
            "yogurt": 1.85,
            "coffee": 6.35,
            "tea": 2.85,
            "sugar": 1.55,
            "flour": 1.25,
            "oil": 4.25,
            "salt": 1.05,
            "pepper": 2.45
        }
    }
];
